---
title: "Practical Statistics for Data Scientists, Chapter 2: Data and Sampling Distributions"
author: "Original Code: Bruce, Peter C., Andrew Bruce and Peter Gedeck | Modifications: Antti Rask"
date: "2023-02-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 2 Data and Sampling Distributions

```{r}
library(boot)
library(conflicted)
    conflicts_prefer(dplyr::filter)
library(tidyverse)
```

## Import the Datasets Needed

```{r}
loans_income  <- read_csv("../data/loans_income.csv") %>% pull()
sp500_px      <- read_csv("../data/sp500_data.csv.gz") %>% 
    select(date = ...1, everything())
```

```{r}
# Figure 2.1

x <- seq(
    from   = -3,
    to     = 3,
    length = 300
)

# 1
tbl <- tibble(x = x, y = dnorm(x))

tbl %>%
    ggplot(aes(x, y)) +
    geom_line(color = "blue") +
    geom_polygon(fill = "blue") +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
    labs(
        x = NULL,
        y = NULL
    ) +
    theme_classic()

# 2
tbl2 <- tibble(x = rnorm(100))

tbl2 %>%
    ggplot(aes(x)) +
    geom_histogram(fill = "red", color = "black", bins = 10) +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
    labs(
        x = NULL,
        y = NULL
    ) +
    theme_classic()
```

## Sampling Distribution of a Statistic

```{r}
# take a simple random sample
samp_data <- tibble(
    income = sample(loans_income, 1000),
    type   = "data_dist"
)

# take a sample of means of 5 values
sample <- sample(loans_income, 1000 * 5)
rep    <- rep(1:1000, rep(5, 1000))

samp_mean_05 <- tibble(sample, rep) %>%
    summarize(
        income = mean(sample),
        .by    = rep
    ) %>%
    mutate(type = "mean_of_5") %>% 
    select(-rep)

# take a sample of means of 20 values
sample2 <- sample(loans_income, 1000 * 20)
rep2    <- rep(1:1000, rep(20, 1000))

samp_mean_20 <- tibble(sample2, rep2) %>%
    summarize(
        income = mean(sample2),
        .by    = rep2
    ) %>%
    mutate(type = "mean_of_20") %>% 
    select(-rep2)

# bind the data.frames and convert type to a factor
income  <- bind_rows(samp_data, samp_mean_05, samp_mean_20) %>% 
    mutate(
        type = factor(
            type,
            levels = c("data_dist", "mean_of_5", "mean_of_20"),
            labels = c("Data",      "Mean of 5", "Mean of 20")
        )
    )

income %>%
    ggplot(aes(income)) +
    geom_histogram(bins = 40) +
    facet_grid(vars(type)) +
    theme_bw()
```

```{r}
# EXTRA: Let's turn it into a function!

calculate_sample_mean <- function(data, n) {
    
    if (n > 50) {
        .replace = TRUE
    } else {
        .replace = FALSE
    }
    
    sample <- sample(loans_income, 1000 * n, replace = .replace)
    rep    <- rep(1:1000, rep(n, 1000))
    
    sample_mean <- tibble(sample, rep) %>%
        summarize(
            income = mean(sample),
            .by    = rep
        ) %>%
        mutate(type = str_glue("mean_of_{n}")) %>% 
        select(-rep)
    
    sample_mean
}

calculate_sample_mean("loans_income", 10)
```

## The Bootstrap

```{r}
# As the calculation uses random samples, results will vary between runs
stat_fun <- function(x, idx) median(x[idx])

boot_obj <- loans_income %>%
    boot(R = 1000, statistic = stat_fun)

boot_obj
```

## Confidence Intervals

```{r}
# figure 2-9 
set.seed(7)
sample20   <- sample(loans_income, 20)
sampleMean <- mean(sample20)
stat_fun   <- function(x, idx) mean(x[idx])
boot_obj   <- boot(sample20, R = 500, statistic = stat_fun)
boot_ci    <- boot.ci(boot_obj, conf = 0.9, type = "basic")
x          <- tibble(mean = boot_obj$t)
ci90       <- tibble(ci = boot_ci$basic[4:5])
ci90_min   <- ci90$ci[1] 
ci90_max   <- ci90$ci[2]

x %>%
    ggplot(aes(mean)) +
    geom_histogram(bins = 40, fill="#AAAAAA") +
    geom_vline(xintercept = sampleMean, linetype = 2) +
    geom_path(aes(ci, 40), data = ci90, linewidth = 1.5) +
    geom_path(aes(ci[1], c(0, 45)), data = ci90, linewidth = 1.5) +
    geom_path(aes(ci[2], c(0, 45)), data = ci90, linewidth = 1.5) +
    geom_label(
        aes(sampleMean, 8, label = str_glue(
            "Sample mean:
                {round(sampleMean)}"
        )
        ),
        size          = 5,
        label.padding = unit(0.5, "lines")
    ) +
    geom_label(
        aes(sampleMean, 44, label = "90% interval"),
        size          = 5,
        label.padding = unit(0.5, "lines")
    ) +
    annotate(
        "text",
        x     = ci90_min,
        y     = 45,
        label = round(ci90_min),
        size  = 6,
        vjust = -1.1
    ) +
    annotate(
        "text",
        x     = ci90_max,
        y     = 45,
        label = round(ci90_max),
        size  = 6,
        vjust = -1.1
    ) +
    scale_y_continuous(expand = c(0, 0), limits = c(0, 60)) +
    labs(x = "", y = "Counts") +
    theme_classic()
```

## Normal Distribution

### Standard Normal and QQ-Plots

```{r}
rnorm(100) %>%
    as_tibble() %>%
    ggplot() +
    stat_qq(aes(sample = value)) +
    geom_abline(slope = 1, intercept = 0, color = "grey") +
    labs(
        x = "Quantile of normal distribution",
        y = "z-score"
    ) +
    theme_classic()
```

## Long-Tailed Distributions

```{r}
nflx <- sp500_px %>% 
    select(NFLX) %>%
    filter(NFLX > 0) %>%
    reframe(nflx = diff(log(NFLX)))

nflx %>%
    ggplot(aes(sample = nflx)) +
    stat_qq() +
    geom_abline(slope = 1, intercept = 0, color = "grey") +
    theme_classic()
```

## Binomial Distribution

```{r}
dbinom(x = 2, size = 5, p = 0.1)

pbinom(2, 5, 0.1)

dbinom(x = 0, size = 200, p = 0.02)
```

## Poisson and Related Distribution

### Poisson Distributions

```{r}
rpois(100, lambda = 2)
```

### Exponential Distribution

```{r}
rexp(n = 100, rate = 0.2)
```

###  Weibull Distribution

```{r}
rweibull(100, 1.5, 5000)
```
